### ISSUE TITLE
BCML crashes on Arch Linux

### ISSUE THREAD

**Issue by SeongGino** [NiceneNerd/BCML#218]
Currently have BCML built from the AUR makepkg (with `yay`), I'm unable to enable/disable any mods and build the BreathOfTheWild_BCML pack without the program crashing midway through.

Terminal output:
```
QSettings::value: Empty key passed
QSettings::value: Empty key passed
/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; std::vector<_Tp, _Alloc>::reference = unsigned char&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```

QSettings bits happens before the window pops up and might be safe to ignore; the `stl_vector.h:1045...` error happens consistently while building, a second or so after the first bit of flavor text (_Finding Koroks..._ etc.)

This happens regardless of mods count - tested with an original setup of about nine active mods, and a from-scratch setup installing one mod, with the same end result.

**Comment by Fxsch** [comment]
I have the same problem but I found that some mods work by adding one after the other and deleting it's folder in "/home/.config/bcml/mods" if it crashed BCML. 

Mods that worked:
- Linkle
- Linkle - Dialogue fix
- Linkle armor icons 
- Everything from the NieR:Automata modpack except for the weapons

Mods that didn't work:
- The weapons mod from the NieR:Automata modpack
- PS4 UI mod by NoPyro

Sometimes when closing it, BCML also made my screen turn black for a few seconds and logged me out of my desktop environment, which might be related to this.

**Comment by Fxsch** [comment]
I've just deleted the version from the AUR and installed BCML with the instructions for other Linux distributions instead and that seems to work. All the mods mentioned above installed without a problem.

**Comment by RamusisTrenksmas** [comment]
Oh, i had same problems, but also succeeded by building it manually and using different Python version. Arch currently uses Python3.10 by default and i noticed that some libraries are not compatible with it. BCML goes much better with something like Python3.8

**Comment by SeongGino** [comment]
> Oh, i had same problems, but also succeeded by building it manually and using different Python version. Arch currently uses Python3.10 by default and i noticed that some libraries are not compatible with it. BCML goes much better with something like Python3.8

Pray tell, how is one to specify Python 3.8, when the rest of their system relies on/uses 3.10, so there are no build tools for the former?

**Comment by rlf89** [comment]
@SeongGino , yes, looks, like you are building it from 3.10.

In my case i just installed python38 from aur repository, then you can access it in terminal typing `python3.8`

installing pip with `python3.8 get-pip.py`

access pip with `python3.8 -m pip`

and from there you can follow github instructions "Building from Source"

**Comment by NiceneNerd** [comment]
@SeongGino You can also try pyenv.

**Comment by SeongGino** [comment]
Still no luck.

The current `python38` AUR package doesn't come with pip, so `python3.8 get-pip.py` fails unless I perform `python3.8 -m ensurepip` first.
I tried installing bcml simply with `python3.8 -m pip install bcml`, but bcml segfaults unless I also install `pyqt` beforehand.
But even with that, the BCML window is just an unchanging white.
Same when building from source.

**Comment by rlf89** [comment]
@SeongGino, i tried to make new build in virtualbox and got same result. But even on my old build bcml gives blank window now, although few months ago it was working nice. I guess here are some library updates, that broke bcml in our case.

**Comment by rlf89** [comment]
wow, ok. I succeeded to run bcml on some old virtualbox image while avoiding making full system update. So current python3.8 and pip modules and bcml are fine. But here is something in system updates, that broke bcml.

**Comment by grinness** [comment]
Hi, 

I have same issue of white screen on both Arch and Manjaro
Installed bcml via pip in virtual env with python38 from AUR.
See:

https://github.com/NiceneNerd/BCML/issues/278

Any advice?

Thanks

**Comment by rlf89** [comment]
I succeeded to run it by doing this:

1. Install bcml any way.
2. python3.8 -m pip install pywebview[gtk]
3. python3.8 -m pip uninstall qtpy

but still wondering why webview stopped working with qt

**Comment by grinness** [comment]
```
python  -m pip install pywebview[gtk]                                                                                                                                                                                                                                                        
zsh: no matches found: pywebview[gtk]
```

the above is with python38 virtualenv activated

**Comment by grinness** [comment]
Got it working.
zsh was causing problem with:

`pip install pywebview[gtk] `

Moved to bash, installed via pip pywebview[gtk]  and uninstalled via pip pyqt

Thanks

**Comment by rlf89** [comment]
Glad it worked! For zsh apparently it works escaping angle brackets :-P

`python3.8 -m pip install pywebview\[gtk\]`

**Comment by SeongGino** [comment]
qtpy definitely seemed to be the issue, because removing it in the containerized python install allows BCML to work - not just showing a window with graphics, but also the creation of mods working without a crash. Only problem being that, at least on my Plasma-based desktop with 150% scaling, the elements are scrunched together in places and not as neat as it otherwise would be with native.
But I'm guessing that's just it running on GTK. Strange problems all around...

**Comment by rlf89** [comment]
qtpy looks for installed libQt5WebEngine implementations. After some digging it seems that all current python implementations are incompatible with recent linux glibc update. Namely it still works with glibc 2.34, but breaks with glibc 2.35 (2022-02-03). QtWebEngineProc dumps core and gives us white screen.

python libQt5WebEngineCore.so.5 ( 5.15.2 ) has to be updated somehow.

**Comment by rlf89** [comment]
I found that python qt5 bindings installed via pacman provides libQt5WebEngineCore.so.5.15.9 for my main python (3.10), and then qt5 graphics work, but i don't know how to bind new libraries with python3.9..

**Comment by NiceneNerd** [comment]
Check a new comment I posted on #278

**Comment by SeongGino** [comment]
Prepending/exporting `QTWEBENGINE_SANDBOX_DISABLE=1` works around the issue with qtpy, indeed.

**Comment by rlf89** [comment]
amazing! so, it is solved :-)

**Comment by Snogard** [comment]
@grinness on zsh you should write:
pip install "pywebview[gtk]"

**Comment by Snogard** [comment]
@SeongGino i have made a [pkgbuild](https://gitlab.com/arch-dragon/packages/bcml-pyenv), it creates a package through pyenv so you won't be bound by your system python version.
In the making of this package i encountered some of the same issues with the AUR package and i discovered that they have to do with file permissions that i think i resolved.
If you end up trying my pkgbuild don't esitate to file issues.

**Comment by SeongGino** [comment]
@Snogard I probably won't for now, since I already have BCML setup through python3.8's pseudo-containerized install and a desktop file that launches it just fine.

I'm still not sure why the PKGBUILDs for BCML kill KDE sessions through their bundled launchers, but mine has no such problems?

**Comment by Snogard** [comment]
me too, with the a normal pyenv installation i can too launch bcml from a desktop file without issues.

One of my firsts workarounds for the crashing was making a desktop file with "kitty devour bcml" on the Exec so that it crashes kitty  instead (i think), so maybe the problem has something to do with the process tree.

Also i tried with the normal desktop file but with Terminal=true and the result was bcml running inside Konsole and upon closing i could see in red character a warning about bcml or sh crashing (yes sh) and konsole would remain opened (without the possibility of writing any commands) until manually closed. That's way i ended up using kitty instead.

Then i looked at the code and after a little investigation it seems that [this line](https://github.com/NiceneNerd/BCML/blob/15e13634004f992c8ba7cd1b526c050936bf91f6/bcml/__main__.py#L43) could be the culprit.
I did try to substitute it with a print and the program closes just fine without crashes, but i don't know if doing this can cause problems later on. For what i understand you shouldn't have any reason to manually close process group as they are terminated automatically when the user closes the application.
Keep in mind that i'm not well versed with python so i could be completely wrong here.

**Comment by ibrokemypie** [comment]
> @SeongGino i have made a [pkgbuild](https://gitlab.com/arch-dragon/packages/bcml-pyenv), it creates a package through pyenv so you won't be bound by your system python version. In the making of this package i encountered some of the same issues with the AUR package and i discovered that they have to do with file permissions that i think i resolved. If you end up trying my pkgbuild don't esitate to file issues. Launching from the desktop file will crash your kde session so for now don't use that.

I wrote the aur pkgbuild for bcml initially, but don't really use it myself and am not invested in maintaining. If you or anyone else would like to take over as maintainer just let me know.


Current state is still using 3.10 (didn't even know about that problem til today!) and while it is building fine, the new maturin based binaries don't even run on my machine for whatever (including ones when built in pyenv just following the build steps outside of the ABS), so I can't even test the package at this point
